#include <iostream>
using namespace std;

int main() {
    cout << "****** Welcome to the Tech Store Purchase Invoice Generator ******" << endl;
    cout << "What would you like to purchase?" << endl;
    cout << "We have a variety of products that are currently available." << endl;
    cout << "1. Laptop - $999.99" << endl;
    cout << "2. Smartphone - $699.99" << endl;
    cout << "3. Tablet - $399.99" << endl;
    cout << "4. Headphones - $199.99" << endl;
    cout << "5. Smartwatch - $299.99" << endl;
    cout << "6. Gaming mouse - $49.99" << endl;
    cout << "7. Mechanical keyboard - $89.99" << endl;
    cout << "8. Monitor - $249.99" << endl;
    cout << "9. External hard drive - $129.99" << endl;
    cout << "10. Computer - $1099.99" << endl;
	cout << "Don't include ' ' when listing the names of the item" << endl;
    cout << "Enter the name of Tech item #1:  ";
	string item1;
    cin >> item1;
	cout << "Enter the price of Tech item #1:  ";
    double price1;
	cin >> price1;
	cout << "Enter the name of Tech item #2:  ";
	string item2;
	cin >> item2;
	cout << "Enter the price of Tech item #2:  ";
    double price2;
	cin >> price2;
	cout << "Enter the name of Tech item #3:  ";
	string item3;
	cin >> item3;
    cout << "Enter the price of Tech item #3:  ";
	double price3;
	cin >> price3;
	cout << "Enter the name of Tech accessory #1:  ";
	string accessory1;
	cin >> accessory1;
	cout << "Enter the price of Tech accessory #1:  ";
	double accessoryPrice1;
	cin >> accessoryPrice1;
	cout << "Enter the name of Tech accessory #2:  ";
	string accessory2;
	cin >> accessory2;
	cout << "Enter the price of Tech accessory #2:  ";
	double accessoryPrice2;
	cin >> accessoryPrice2;
	cout << "Enter the name of Tech accessory #3:  ";
	string accessory3;
	cin >> accessory3;
	cout << "Enter the price of Tech accessory #3:  ";
	double accessoryPrice3;
	cin >> accessoryPrice3;
    double laptop = 999.99;
    double smartphone = 699.99;
    double tablet = 399.99;
    double headphones = 399.99;
    double smartwatch = 299.99;
    double gamingMouse = 49.99;
    double mechanicalKeyboard = 89.99;
    double monitor = 249.99;
    double externalHardDrive = 129.99;
	double computer = 1099.99;
	double subtotal = price1 + price2 + price3 + accessoryPrice1 + accessoryPrice2 + accessoryPrice3;
	double tax = subtotal * 0.095;
	double total = subtotal + tax;
	cout << "=========== TECH STORE INVOICE ===========" << endl;
	cout << "Item 1: " << item1 << " - $" << price1 << endl;
	cout << "Item 2: " << item2 << " - $" << price2 << endl;
	cout << "Item 3: " << item3 << " - $" << price3 << endl;
	cout << "Accessory 1: " << accessory1 << " - $" << accessoryPrice1 << endl;
	cout << "Accessory 2: " << accessory2 << " - $" << accessoryPrice2 << endl;
	cout << "Accessory 3: " << accessory3 << " - $" << accessoryPrice3 << endl;
	cout << "Subtotal: $" << subtotal << endl;
	cout << "Sales Tax (9.5%): $" << tax << endl;
	cout << "Total: $" << total << endl;
	cout << "=========================================" << endl;
	return 0;
}